env:
  contexts:
  - excludePaths: []
    name: baseline
    urls:
    - https://ottiu.com/
  parameters:
    failOnError: true
    progressToStdout: true
jobs:
- parameters:
    enableTags: false
    maxAlertsPerRule: 10
  type: passiveScan-config
- parameters:
    maxDuration: 1
    url: https://ottiu.com/
  type: spider
- parameters:
    maxDuration: 0
  type: passiveScan-wait
- parameters:
    format: Long
    summaryFile: /home/zap/zap_out.json
  rules: []
  type: outputSummary
- parameters:
    reportDescription: ''
    reportDir: /zap/wrk/
    reportFile: zap-d177bb09-5fa8-4ece-95d8-4d7950644d0b.json
    reportTitle: ZAP Scanning Report
    template: traditional-json
  type: report
